import SwiftUI
import SwiftData

struct PayeeNoteEditSheet: View {
    @Environment(\.modelContext) private var modelContext
    @Environment(\.dismiss) private var dismiss

    let matchKey: String
    let samplePayee: String
    let autoGeneratedName: String
    let onSaved: () -> Void

    @State private var displayName: String = ""
    @State private var notes: String = ""
    @State private var saveError: String?

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    LabeledContent("Bank payee") {
                        Text(samplePayee)
                            .foregroundStyle(.secondary)
                            .multilineTextAlignment(.trailing)
                    }
                    LabeledContent("Auto label") {
                        Text(autoGeneratedName)
                            .foregroundStyle(.secondary)
                            .multilineTextAlignment(.trailing)
                    }
                } header: {
                    Text("Reference")
                } footer: {
                    Text("Your label is saved and reused whenever this payee appears in future imports.")
                }

                Section("Your label") {
                    TextField("Display name", text: $displayName, prompt: Text(autoGeneratedName))
                    TextField("Notes", text: $notes, prompt: Text("e.g. Winter Fuel Payment"), axis: .vertical)
                        .lineLimit(3...6)
                }

                if let saveError {
                    Section {
                        Text(saveError)
                            .foregroundStyle(.red)
                            .font(.caption)
                    }
                }
            }
            .navigationTitle("Payee label")
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") { save() }
                }
            }
            .onAppear(perform: loadExisting)
        }
        .frame(minWidth: 420, minHeight: 320)
    }

    private func loadExisting() {
        displayName = autoGeneratedName
        do {
            if let existing = try PayeeNoteService.note(for: matchKey, in: modelContext) {
                if !existing.displayName.isEmpty {
                    displayName = existing.displayName
                }
                notes = existing.notes
            }
        } catch {
            saveError = error.localizedDescription
        }
    }

    private func save() {
        saveError = nil
        do {
            try PayeeNoteService.upsert(
                matchKey: matchKey,
                displayName: displayName,
                notes: notes,
                samplePayee: samplePayee,
                in: modelContext
            )
            onSaved()
            dismiss()
        } catch {
            saveError = error.localizedDescription
        }
    }
}
